run:
    python app.py --setup_file ./setup.py --runner DataflowRunner --region us-east1 --project cs-data-warehouse-dev --temp_location gs://cs-data-warehouse-dev/dataflow/tmp/ --num_workers 7 --staging_location gs://cs-data-warehouse-dev/dataflow/stage/ --service_account_email 176285672230-compute@developer.gserviceaccount.com 


